spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/auth
    username: post
    password: post
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    security:
      jwt:
        access-expiration: 900000
        refresh-expiration: 2592000000
        private-key-path: services/auth/src/main/resources/keys/private.pem
        public-key-path: services/auth/src/main/resources/keys/public.pem

server:
  port: 8095
