spring:
  data:
    mongodb:
      username: glite
      password: GliteEcom$200
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090

