spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

management:
  tracing:
    sampling:
      probability: 1.0
